from: mac
envs:
  version: 1.0
  build: 1.0
  
stages:
  build:
    - rm -rf bin/
    # 下一条指令开启xcode工程的默认编译
    # 一般需要指定以下参数:
    # --iosPath 输出路径， 默认是 bin/ios
    # --iosName IPA文件名，默认是output.ipa
    # -v, --version xcode版本号 默认是 8.3.3 
    # -p xcode project
    # 更多参数查看左边构建参数配置
    - plugin_xcode -p m2048.xcodeproj
    
    # 下一条指令开启IOS签名，这个步骤需要您先在证书管理中上传您的个人证书
    # 一般需要指定以下参数：
    # --certId 上传证书时填写的证书名字
    # --password 证书密码
    # --codeSignIdentity 您申请的证书的ID，类似于 "iPhone Developer: xxxx"
    # --provisioningProfile 您申请的证书的provision profile，类似于 "2287a324-856c-4ccd-bb90-047baafbbe42"
    # 更多参数查看左边构建参数配置
    - plugin_ios_sign --certID soda --password 123456 --codeSignIdentity "iPhone Developer: junchi he (22AYX4B947)" --provisioningProfile "56c18d4d-c356-4069-81b1-4cf1ea61043f"

    # 下一条指令是用于上传您的ipa文件到fir.im，在上传之前您需要先到http://fir.im申请账号并且生成一个token
    # 一般需要指定一下参数：
    # --build 构建版本号
    # --bundleId 你代码的包名
    # --file 需要上传的文件
    # --name 在fir.im上面的显示名字
    # --token 您在fir.im生成的token
    # --type 上传包的类型（android或者ios)
    # --version 包的版本
    - plugin_fir --build "#{build}" --bundleId com.soda.m2048 --file bin/ios/output.ipa  --name 2048 --token "#{fir.token}" --type ios --version "#{version}"
    # 用于上传构建产物到腾讯云对象存储系统 
    
    # Usage: <main class> [options]
    #   Options:
    #     --appid
    #        COS APPID
    #     --bucketName
    #        The bucket name in COS
    #     --bucketPath
    #        存储文件到bucket中的folder
    #     --files
    #        需要上传的文件，支持正则匹配，例如 /bin/*.apk
    #     -r, --region
    #        COS 区域，默认是广州
    #        Default: ap_guangzhou
    #        Possible Values: [ap_beijing_1, ap_beijing, ap_shanghai, ap_guangzhou, ap_chengdu, ap_singapore, ap_hongkong, na_toronto, eu_frankfurt]
    #     --secretId
    #        COS API secret id
    #     --secretKey
    #        COS API secret key
    
    - plugin_cos --appid "#{cos.appid}" --bucketName soda --bucketPath / --files bin/ios/*.ipa --region ap_guangzhou --secretId "#{cos.secretId}" --secretKey "#{cos.secretKey}"
      